### ISSUE TITLE
Uploaded certificate is not displayed in Import Certificate page

### ISSUE THREAD

**Issue by OlhaPeculiar** [PeculiarVentures/fortify-tools#178]
on 1:00 minutes at video

https://github.com/user-attachments/assets/fab4a3c2-c027-4330-a380-a2a68d34cda8

**Comment by OleksandrSPV** [comment]
[QuoVadis Trustlink Schweiz AG (1).cer.zip](https://github.com/user-attachments/files/16375820/QuoVadis.Trustlink.Schweiz.AG.1.cer.zip)
Olga used this certificate and as I see the X509Certificate throw error "Data does not match to Certificate ASN1 schema"
<img width="308" alt="image" src="https://github.com/user-attachments/assets/9d5c23cd-5951-438e-a5f0-f710f2be9591">
@microshine Do you have any ideas?

**Comment by microshine** [comment]
The provided certificate file has an incorrect format. Certificate files are only represented in two formats - PEM and DER. The file you provided is in hex format with spaces and line breaks:

```
3082 0637 3082 041f a003 0201 0202 1450 
fe57 881a c830 eab3 cb2f 0f51 42cc bab2 
...
0359 5630 7749 05cb 46ac 442a 695f 1d0f 
41a4 4c56 3642 ffbb d20c 91
```

The x509 module constructor supports hex format, but without spaces and line breaks. Since this file has a non-standard format, it may not be necessary to support it. It might be better to display an error about the incorrect file format when `Data does not match to Certificate ASN1 schema`.

**Comment by OleksandrSPV** [comment]
> it. It might be better to display an error about the incorrect file format when `Data does not match to Certificate ASN1 schema`.

Now we show message

Uploading Screen Recording 2024-11-22 at 13.38.03.mov…

**Comment by microshine** [comment]
If we decide to support this format, the change should be made at the `pvtsutils` level. We need to update the `Convert.isHex` and `Convert.FromHex` methods to support spaces and line breaks.

**Comment by OleksandrSPV** [comment]
@OlhaPeculiar Could you check please here https://fortify-tools.vercel.app/

**Comment by OlhaPeculiar** [comment]
Еverything works at the moment ))
